CREATE DATABASE TESTING;

USE TESTING;

CREATE TABLE MAE_SEXO 
   (	
   SEXO_ID INT IDENTITY(1,1) NOT NULL, 
	NOMBRE VARCHAR(250) NOT NULL, 
	ACTIVO BIT DEFAULT 1 NOT NULL,  
	 CONSTRAINT PK_MAE_SEXO PRIMARY KEY (SEXO_ID)
   );

CREATE TABLE MAE_CLIENTE 
   (	
   CLIENTE_ID INT IDENTITY(1,1) NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO_PATERNO VARCHAR(50) NOT NULL,
	APELLIDO_MATERNO VARCHAR(50) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	SEXO_ID INT NOT NULL,
	DIRECCION VARCHAR(250) NOT NULL,
	CORREO VARCHAR(50) NOT NULL,
	ACTIVO BIT DEFAULT 1 NOT NULL,  
	 CONSTRAINT PK_MAE_CLIENTE PRIMARY KEY (CLIENTE_ID)
   );

   ALTER TABLE MAE_CLIENTE ADD CONSTRAINT FK_MAE_CLIENTE_MAE_SEXO FOREIGN KEY (SEXO_ID)
	  REFERENCES MAE_SEXO (SEXO_ID);