USE [TESTING]
GO
SET IDENTITY_INSERT [dbo].[MAE_SEXO] ON 
GO
INSERT [dbo].[MAE_SEXO] ([SEXO_ID], [NOMBRE], [ACTIVO]) VALUES (1, N'MASCULINO', 1)
GO
INSERT [dbo].[MAE_SEXO] ([SEXO_ID], [NOMBRE], [ACTIVO]) VALUES (2, N'FEMENINO', 1)
GO
INSERT [dbo].[MAE_SEXO] ([SEXO_ID], [NOMBRE], [ACTIVO]) VALUES (3, N'OTRO', 1)
GO
SET IDENTITY_INSERT [dbo].[MAE_SEXO] OFF
GO
